### ISSUE TITLE
Rename warrior level 42 "Mastery of Destruction" -> "Scorching Strikes"

### ISSUE THREAD

**Issue by WeaverThree** [atmafox/FFRPG4e#278]
One is in Double Cut on page 54 and one is in Dragon Power on page 54/55.

**Comment by BrunoCarvalhoPaula** [comment]
The level 42 one should be called Scorching Strikes, as per info on the http://ffrpg4e.wikidot.com/playtest Page. The Page is now blank but you can click HISTORY to check the november 8 revision to check it

**Comment by WeaverThree** [comment]
Thank you!

**Comment by BrunoCarvalhoPaula** [comment]
Addressed in b-401
