### ISSUE TITLE
Item lists

### ISSUE THREAD

**Issue by atmafox** [atmafox/FFRPG4e#28]
Requires #108 #109 as data source and #110 to be completed.

**Comment by atmafox** [comment]
Mostly done on other tickets but I forgot to enter the rest of the weapons so I'll get that knocked out.  Also, the restorative items.

**Comment by atmafox** [comment]
We will need to work out how to do the header when many weapon types either have multiple flavours of damage (puncture/cut/crush in heavy weapons) or elements (player's choice air or earth vs earth on polearms)

**Comment by BrunoCarvalhoPaula** [comment]
In boardgame iconography, the symbol / generally represents a "either-or" choice. You can see examples here, 
![image](https://user-images.githubusercontent.com/54651029/68795104-0ed08e80-062f-11ea-9a2d-1131db0f0587.png)
here,
![image](https://user-images.githubusercontent.com/54651029/68795192-3889b580-062f-11ea-9363-5f671895b6fa.png)
and here:
![image](https://user-images.githubusercontent.com/54651029/68795237-50f9d000-062f-11ea-8992-c5080704bacc.png)


So I'm happy with having "cut / crush" to signal the weapons are either cut or crush, for example.
