### ISSUE TITLE
New release edits - Bruno

### ISSUE THREAD

**Issue by atmafox** [atmafox/FFRPG4e#29]
Bruno plans to add his new release edits

**Comment by BrunoCarvalhoPaula** [comment]
Question: What is better?
a), to jump over Revised edition and go directly to creating a new book with all erratas included (FFRPG 4e Gold? Collector's Edition? Director's Cut?) 
b) redo Revised edition AND Errata document on LaTeX, then copy the files into a new book and merge them there, keeping the older books for history/reference purposes?

**Comment by BrunoCarvalhoPaula** [comment]
Do you want me to push branches replacing the revised/anything.tex files or should I create a new folder (probably remaster) so I upload the files as remaster/anything.tex ?

**Comment by atmafox** [comment]
Let's go with replacing.  Git will keep the history for us so we don't need
to worry about it.

**Comment by BrunoCarvalhoPaula** [comment]
Almost all done. Closing this issue and opening a new one with the last things
