### ISSUE TITLE
Inconsistent weapon & shield 

### ISSUE THREAD

**Issue by BrunoCarvalhoPaula** [atmafox/FFRPG4e#295]
- [x] Page 29 - 'Adept weapons - weapons & shield'
- [x] Page 38 - 'Nature warrior - weapons & shield'
- [x]  52 - 'Warrior weapons - weapon & shield'
- [x] Page 56 - 'Heavenly Warrior - Heavy weapons & shield'
- [x] Page 68 - 'Equip Axe - Heavy Weapon & Shield'
- [x] Page 96 - 'Weapons can be classified as Light Swords / Knives, Heavy Weapons & Shield, Heavy Weapons,'
- [x] Page 102 -'Weapons & Shields'

Inconsistent plurality and usage of "Heavy" for Weapon & Shield, though 102 is probably fine even if it is different.

**Comment by WeaverThree** [comment]
Working on these as I go through job stuff, made it into a checklist.

**Comment by atmafox** [comment]
Going to go with `Weapons & Shields`

**Comment by atmafox** [comment]
Resolved in #313
